### ISSUE TITLE
Question about require { resolve } from url 

### ISSUE THREAD

**Issue by voodoologic** [securisec/condoit#3]
https://github.com/securisec/condoit/blob/master/src/index.ts#L3
How is this dependency fullfilled?

**Comment by joshrahman** [comment]
@voodoologic https://nodejs.org/api/url.html#url_url_resolve_from_to

**Comment by securisec** [comment]
https://nodejs.org/api/url.html#url_url_resolve_from_to

**Comment by voodoologic** [comment]
I see, I'm trying to build a browser application and I'm not too familiar with node.  Thanks for the clarification and quick response.

**Comment by securisec** [comment]
This implementation of the phabricator api is not browser compatible unfortunately.
