### ISSUE TITLE
Allow passing Axios instance into Condoit client constructor

### ISSUE THREAD

**Issue by tovbinm** [securisec/condoit#9]
It would be a great addition to allow passing and Axios http client instance into Condoit client. That way developers would be able to customize different http settings easily. Example:
```typescript
import {axios,AxiosInstance} from 'axios';
import {Condoit} from 'condoit';

const axios: AxiosInstance = axios.create({ timeout: 300000 }); // for example increase a timeout
const condoit = new Condoit('https://path/to/phabricator', 'api-token', axios)
```

**Comment by securisec** [comment]
@tovbinm the feature request has been added. Feel free to give it a try and provide feedback before I publish to npm

**Comment by tovbinm** [comment]
Thank you! This is great!

**Comment by securisec** [comment]
@tovbinm is it working as you expected it? I made a quick change, but I cannot test it at the moment. If it is working as you expected by passing your own custom axios instance, then I can go ahead and publish it.

**Comment by tovbinm** [comment]
Would I need to clone the repo and publish locally?

**Comment by securisec** [comment]
It is now published v2.1.0

**Comment by tovbinm** [comment]
Thanks. I will let you know.

**Comment by tovbinm** [comment]
I get `name.toUpperCase is not a function` error when trying to pass an axios instance

**Comment by securisec** [comment]
Can you be a bit more specific on the error message? It doesn’t appear to be part of condoit. If it is, feel free to make a pull request with the fix

**Comment by tovbinm** [comment]
this can be related - https://stackoverflow.com/questions/49948400/react-axios-get-not-working-log-out-name-touppercase-is-not-a-function

**Comment by securisec** [comment]
Could be. Can you show me how you are instantiating the Condoit constructor? Like new Condoit…. The third argument are the headers and the fourth is the axios instance. If you are not setting headers, then pass {} as the third argument. 

Also, the lib is not tested against browsers, so I am not fully sure what will work. I wrote it mostly for server side operations.

**Comment by tovbinm** [comment]
ok, my bad! it's working as expected.
Instead of `const client = new Condoit(config.server_url, config.token, axios)` I needed to do `const client = new Condoit(config.server_url, config.token, {}, axios)`

**Comment by tovbinm** [comment]
Thank you!
